### ISSUE TITLE
dev-db: migrate public schema to new_one or screw it

### ISSUE THREAD

**Issue by psineur** [TheRealGD/therealgd#56]
Subj.

Migrating from old RDS - i had to use pg_dump+pg_restore from old, where schema used was 'public'.
Take a look at the DB and decide if this is something that needs fixing or not.

It's probably good idea to look at https://github.com/TheRealGD/therealgd/pull/54 first.

@NathanDeckinga plz self-assign when you accept invite to the org.

**Comment by NathanDeckinga** [comment]
I'm in.

**Comment by psineur** [comment]
@NathanDeckinga  https://github.com/TheRealGD/therealgd/invitations

**Comment by NathanDeckinga** [comment]
That did it - I can now edit some things I couldn't previously.  Thanks.

**Comment by NathanDeckinga** [comment]
Okay - I have your answer.  If all of the DBs look like therealgd_dev, then everything exists in the public schema and no user defined schemas exist.  It shouldn't hurt anything to leave everything in the public schema, but if you want to go full postgresql and have it in a user schema, that's relatively easy.  I see 22 tables - so the thing to do is alter the tables.  If it was any schema other than public, I would suggest just renaming the schema.

* Create the new schema you want everything to be in
* Change the default search path for the user so that this doesn't happen in the future
* Alter tables to be in the right/new schema

I have the commands ready to run.
